#!/usr/bin/env python3
"""
Complete parameter mapping for all Phonon functions
Extracted from compositional_compiler.rs
"""

# Complete mapping of function names to their parameters
COMPLETE_PARAMETERS = {
    # ===== ALREADY IN METADATA (hand-written) =====
    "lpf": ["cutoff", "q"],
    "hpf": ["cutoff", "q"],
    "bpf": ["cutoff", "q"],
    "notch": ["cutoff", "q"],
    "bq_hp": ["frequency", "q"],
    "bq_lp": ["frequency", "q"],
    "brown_noise": [],
    "adsr": ["attack", "decay", "sustain", "release"],
    "ad": ["attack", "decay"],
    "asr": ["gate", "attack", "release"],
    "reverb": ["room_size", "damping", "mix"],
    "chorus": ["rate", "depth", "mix"],
    "delay": ["time", "feedback", "mix"],
    "distort": ["drive", "mix"],
    "s": ["pattern"],
    "gain": ["amount"],
    "pan": ["position"],
    "speed": ["rate"],
    "begin": ["position"],
    "end": ["position"],
    "sine": ["freq"],
    "saw": ["freq"],
    "square": ["freq"],
    "tri": ["freq"],
    "fast": ["factor"],
    "slow": ["factor"],
    "every": ["n", "transform"],
    "shuffle": ["amount"],
    "chop": ["n"],
    "striate": ["n"],
    "slice": ["n", "indices"],
    "scramble": ["n"],
    "rev": [],
    "palindrome": [],
    "mirror": [],
    "rotL": ["n"],
    "rotR": ["n"],
    "swing": ["amount"],
    "late": ["amount"],
    "early": ["amount"],
    "offset": ["amount"],
    "legato": ["factor"],
    "staccato": ["factor"],
    "stretch": [],
    "linger": ["factor"],
    "stutter": ["n"],
    "ply": ["n"],
    "dup": ["n"],
    "iter": ["n"],
    "iterBack": ["n"],
    "echo": ["times", "time", "feedback"],
    "degrade": [],
    "degradeBy": ["probability"],
    "gap": ["n"],
    "segment": ["n"],
    "zoom": ["begin", "end"],
    "compress": ["begin", "end"],
    "compressGap": ["begin", "end"],
    "fit": ["n"],
    "spin": ["n"],
    "loop": ["n"],
    "loopAt": ["cycles"],
    "chew": ["n"],
    "fastGap": ["factor"],
    "discretise": ["n"],
    "binary": ["n"],
    "range": ["min", "max"],
    "reset": ["n"],
    "restart": ["n"],
    "loopback": [],
    "squeeze": ["n"],
    "quantize": ["steps"],
    "smooth": ["amount"],
    "exp": ["base"],
    "log": ["base"],
    "walk": ["step_size"],
    "focus": ["cycle_begin", "cycle_end"],
    "trim": ["begin", "end"],
    "wait": ["cycles"],
    "accelerate": ["rate"],
    "inside": ["begin", "end", "transform"],
    "outside": ["begin", "end", "transform"],
    "within": ["begin", "end", "transform"],
    "superimpose": ["transform"],
    "chunk": ["n", "transform"],
    "sometimes": ["transform"],
    "often": ["transform"],
    "rarely": ["transform"],
    "sometimesBy": ["probability", "transform"],
    "almostAlways": ["transform"],
    "almostNever": ["transform"],
    "always": ["transform"],
    "whenmod": ["modulo", "offset", "transform"],
    "mask": ["pattern"],
    "weave": ["count"],
    "degradeSeed": ["seed"],
    "undegrade": [],
    "humanize": ["time_var", "velocity_var"],
    "euclid": ["pulses", "steps"],
    "flanger": ["depth", "rate", "feedback"],
    "granular": ["source", "grain_size_ms", "density", "pitch"],
    "limiter": ["input", "threshold"],
    "moog": ["input", "cutoff", "resonance"],
    "moog_hz": ["cutoff", "resonance"],
    "pink_noise": [],
    "pitch_shift": ["input", "semitones"],
    "plate": ["pre_delay", "decay", "diffusion", "damping", "mod_depth", "mix"],
    "pulse": ["frequency", "pulse_width"],
    "reverb_stereo": ["wet", "time"],
    "ring_mod": ["signal1", "signal2"],
    "sample_hold": ["input", "trigger"],
    "superchip": ["freq", "vibrato_rate", "vibrato_depth"],
    "superfm": ["freq", "mod_ratio", "mod_index"],
    "superhat": ["bright", "sustain"],
    "superkick": ["freq", "pitch_env", "sustain", "noise_amt"],
    "superpwm": ["freq", "pwm_rate", "pwm_depth"],
    "supersaw": ["freq", "detune", "voices"],
    "supersnare": ["freq", "snappy", "sustain"],
    "svf_hp": ["frequency", "resonance"],
    "svf_lp": ["frequency", "resonance"],
    "vco": ["frequency", "waveform", "pulse_width"],
    "vocoder": ["modulator", "carrier", "num_bands"],
    "white_noise": [],
    "xfade": ["signal_a", "signal_b", "position"],
    "xline": ["start", "end", "duration"],

    # ===== ADDITIONAL FUNCTIONS FROM GENERATED STUBS (need params added) =====
    "additive": ["freq", "amplitudes"],
    "allpass": ["coefficient"],
    "amp": ["amplitude"],
    "amp_follower": ["attack_time", "release_time", "window_size"],
    "ar": ["attack", "release"],
    "attack": ["time"],
    "bipolar": [],
    "bitcrush": ["bits", "sample_rate"],
    "blip": ["frequency"],
    "bq_bp": ["frequency", "q"],
    "bq_notch": ["frequency", "q"],
    "cat": ["patterns"],
    "choose": ["options"],
    "coarse": ["factor"],
    "comb": ["frequency", "feedback"],
    "comp": ["threshold", "ratio", "attack", "release", "makeup_gain"],
    "compressor": ["threshold", "ratio", "attack", "release", "makeup_gain"],
    "convolution": [],
    "convolve": [],
    "cosine": ["freq"],
    "curve": ["start", "end", "duration", "curve"],
    "cut": ["group"],
    "cut_group": ["group"],
    "decimator": ["factor"],
    "dist": ["drive", "mix"],
    "distortion": ["drive", "mix"],
    "djf": ["value"],
    "envelope": ["attack", "decay", "sustain", "release"],
    "env": ["attack", "decay", "sustain", "release"],
    "env_trig": ["attack", "decay", "sustain", "release"],
    "eq": ["low_freq", "low_gain", "low_q", "mid_freq", "mid_gain", "mid_q", "high_freq", "high_gain", "high_q"],
    "expand": ["threshold", "ratio", "attack", "release"],
    "expander": ["threshold", "ratio", "attack", "release"],
    "fchorus": ["separation", "variation", "mod_frequency"],
    "fm": ["carrier_freq", "modulator_freq", "mod_index"],
    "fm_crossmod": ["carrier", "modulator", "mod_depth"],
    "fmcrossmod": ["carrier", "modulator", "mod_depth"],
    "formant": ["source", "f1", "f2", "f3", "bw1", "bw2", "bw3"],
    "freeze": ["trigger"],
    "fundsp_chorus": ["separation", "variation", "mod_frequency"],
    "hurry": ["factor"],
    "if": ["condition", "then_signal", "else_signal"],
    "impulse": ["frequency"],
    "irand": ["max"],
    "karplus_strong": ["frequency", "damping"],
    "lag": ["input", "lag_time"],
    "latch": ["gate"],
    "line": ["start", "end"],
    "moog_ladder": ["input", "cutoff", "resonance"],
    "multitap": ["time", "taps"],
    "n": ["value"],
    "noise": [],
    "note": ["value"],
    "organ": ["freq"],
    "organ_hz": ["freq"],
    "parametric_eq": ["low_freq", "low_gain", "low_q", "mid_freq", "mid_gain", "mid_q", "high_freq", "high_gain", "high_q"],
    "pan2_l": ["input", "position"],
    "pan2_r": ["input", "position"],
    "peak_follower": ["attack_time", "release_time"],
    "ph": ["rate", "depth", "feedback", "stages"],
    "phaser": ["rate", "depth", "feedback", "stages"],
    "pingpong": ["time", "feedback"],
    "pink": [],
    "pluck": ["frequency", "damping"],
    "pm": ["carrier_freq", "modulation", "mod_index"],
    "probe": ["filename", "duration"],
    "rand": [],
    "release": ["time"],
    "resonz": ["frequency", "q"],
    "rhpf": ["cutoff", "resonance"],
    "ring": ["frequency"],
    "rlpf": ["cutoff", "resonance"],
    "rms": ["window_size"],
    "run": ["n"],
    "saw_hz": ["frequency"],
    "saw_trig": ["freq"],
    "sawwave": [],
    "sc_comp": ["sidechain_input", "threshold", "ratio", "attack", "release"],
    "scan": ["start", "end"],
    "schmidt": ["high_threshold", "low_threshold"],
    "segments": ["levels_string", "times_string"],
    "select": ["index"],
    "sidechain_comp": ["sidechain_input", "threshold", "ratio", "attack", "release"],
    "sidechain_compressor": ["sidechain_input", "threshold", "ratio", "attack", "release"],
    "sine_trig": ["freq"],
    "sinewave": [],
    "slowcat": ["patterns"],
    "soft_saw": ["frequency"],
    "soft_saw_hz": ["frequency"],
    "square_hz": ["frequency"],
    "square_trig": ["freq"],
    "squarewave": [],
    "stack": ["patterns"],
    "struct": ["pattern"],
    "svf_bp": ["frequency", "resonance"],
    "svf_notch": ["frequency", "resonance"],
    "tape": ["time", "feedback", "wow_rate", "wow_depth", "flutter_rate", "flutter_depth", "saturation", "mix"],
    "tapedelay": ["time", "feedback", "wow_rate", "wow_depth", "flutter_rate", "flutter_depth", "saturation", "mix"],
    "tap": ["filename", "duration"],
    "trem": ["rate", "depth"],
    "tremolo": ["rate", "depth"],
    "tri_trig": ["freq"],
    "triangle": ["freq"],
    "triangle_hz": ["frequency"],
    "triwave": [],
    "unipolar": [],
    "unit": ["mode"],
    "vib": ["rate", "depth"],
    "vibrato": ["rate", "depth"],
    "vowel": ["pattern"],
    "waveguide": ["frequency", "damping", "pickup_position"],
    "wavetable": ["frequency"],
    "wchoose": ["options"],
    "wedge": ["a", "b", "pattern"],
    "sew": ["a", "b", "pattern"],
    "mix": ["a", "b", "mix"],
    "timer": [],
}

def get_params_for_function(func_name):
    """Get parameter list for a function"""
    return COMPLETE_PARAMETERS.get(func_name, [])

def get_all_functions():
    """Get all function names"""
    return sorted(COMPLETE_PARAMETERS.keys())

if __name__ == "__main__":
    print(f"Total functions: {len(COMPLETE_PARAMETERS)}")
    print("\nFunctions with parameters:")
    for func, params in sorted(COMPLETE_PARAMETERS.items()):
        if params:
            print(f"  {func}: {params}")
    print(f"\nFunctions without parameters:")
    for func, params in sorted(COMPLETE_PARAMETERS.items()):
        if not params:
            print(f"  {func}")
