#!/bin/bash
# Script to generate stub metadata for all missing functions in compositional_compiler.rs

set -e

echo "Extracting function names from compositional_compiler.rs..."

# Extract all function names from the compiler dispatch table
grep -oP '"\K[a-z_][a-z0-9_]*(?="\s*=>)' src/compositional_compiler.rs | sort -u > /tmp/all_functions_clean.txt

echo "Found $(wc -l < /tmp/all_functions_clean.txt) total functions in compiler"

# Extract functions that already have metadata
grep -oP 'm\.insert\("\K[^"]+' src/modal_editor/completion/function_metadata.rs | sort > /tmp/metadata_functions.txt

echo "Found $(wc -l < /tmp/metadata_functions.txt) functions with existing metadata"

# Find missing functions
comm -23 /tmp/all_functions_clean.txt /tmp/metadata_functions.txt > /tmp/missing_functions.txt

MISSING_COUNT=$(wc -l < /tmp/missing_functions.txt)
echo "Found $MISSING_COUNT functions missing metadata"

# Generate stub metadata file
cat > src/modal_editor/completion/generated_metadata_stubs.rs <<'EOF'
// AUTO-GENERATED FILE - Generated by generate_stubs.sh
// This file contains stub metadata for functions that don't yet have hand-written metadata.
// These stubs will be merged with the hand-written metadata in function_metadata.rs

use std::collections::HashMap;
use super::function_metadata::{FunctionMetadata, ParamMetadata};

lazy_static::lazy_static! {
    /// Auto-generated stub metadata for functions missing hand-written metadata
    pub static ref GENERATED_STUBS: HashMap<&'static str, FunctionMetadata> = {
        let mut m = HashMap::new();

EOF

# Generate a stub entry for each missing function
while IFS= read -r func; do
    cat >> src/modal_editor/completion/generated_metadata_stubs.rs <<EOF
        m.insert("$func", FunctionMetadata {
            name: "$func",
            description: "TODO: Add description for $func",
            params: vec![],
            example: "",
            category: "Unknown",
        });

EOF
done < /tmp/missing_functions.txt

# Close the lazy_static block
cat >> src/modal_editor/completion/generated_metadata_stubs.rs <<'EOF'
        m
    };
}
EOF

echo "Generated stub metadata file: src/modal_editor/completion/generated_metadata_stubs.rs"
echo "Generated $MISSING_COUNT stub entries"

# Update the mod.rs to include the generated file
if ! grep -q "pub mod generated_metadata_stubs" src/modal_editor/completion/mod.rs 2>/dev/null; then
    echo "pub mod generated_metadata_stubs;" >> src/modal_editor/completion/mod.rs
    echo "Added generated_metadata_stubs to mod.rs"
fi

echo ""
echo "Missing functions:"
cat /tmp/missing_functions.txt

echo ""
echo "Done! To use these stubs, update function_metadata.rs to merge GENERATED_STUBS with FUNCTION_METADATA"
