// AUTO-GENERATED FILE - Generated by generate_stubs.sh
// This file contains stub metadata for functions that don't yet have hand-written metadata.
// These stubs will be merged with the hand-written metadata in function_metadata.rs

use super::function_metadata::{FunctionMetadata, ParamMetadata};
use std::collections::HashMap;

lazy_static::lazy_static! {
    /// Auto-generated stub metadata for functions missing hand-written metadata
    pub static ref GENERATED_STUBS: HashMap<&'static str, FunctionMetadata> = {
        let mut m = HashMap::new();

        m.insert("additive", FunctionMetadata {
            name: "additive",
            description: "TODO: Add description for additive",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "amplitudes",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("allpass", FunctionMetadata {
            name: "allpass",
            description: "TODO: Add description for allpass",
            params: vec![
                ParamMetadata {
                    name: "coefficient",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("amp", FunctionMetadata {
            name: "amp",
            description: "TODO: Add description for amp",
            params: vec![
                ParamMetadata {
                    name: "amplitude",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("amp_follower", FunctionMetadata {
            name: "amp_follower",
            description: "TODO: Add description for amp_follower",
            params: vec![
                ParamMetadata {
                    name: "attack_time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release_time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "window_size",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("ar", FunctionMetadata {
            name: "ar",
            description: "TODO: Add description for ar",
            params: vec![
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("attack", FunctionMetadata {
            name: "attack",
            description: "TODO: Add description for attack",
            params: vec![
                ParamMetadata {
                    name: "time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Modifiers",
        });

        m.insert("bipolar", FunctionMetadata {
            name: "bipolar",
            description: "TODO: Add description for bipolar",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m.insert("bitcrush", FunctionMetadata {
            name: "bitcrush",
            description: "TODO: Add description for bitcrush",
            params: vec![
                ParamMetadata {
                    name: "bits",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "sample_rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("blip", FunctionMetadata {
            name: "blip",
            description: "TODO: Add description for blip",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("bq_bp", FunctionMetadata {
            name: "bq_bp",
            description: "TODO: Add description for bq_bp",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("bq_notch", FunctionMetadata {
            name: "bq_notch",
            description: "TODO: Add description for bq_notch",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("cat", FunctionMetadata {
            name: "cat",
            description: "TODO: Add description for cat",
            params: vec![
                ParamMetadata {
                    name: "patterns",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("choose", FunctionMetadata {
            name: "choose",
            description: "TODO: Add description for choose",
            params: vec![
                ParamMetadata {
                    name: "options",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("coarse", FunctionMetadata {
            name: "coarse",
            description: "TODO: Add description for coarse",
            params: vec![
                ParamMetadata {
                    name: "factor",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("comb", FunctionMetadata {
            name: "comb",
            description: "TODO: Add description for comb",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "feedback",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("comp", FunctionMetadata {
            name: "comp",
            description: "TODO: Add description for comp",
            params: vec![
                ParamMetadata {
                    name: "threshold",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "ratio",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "makeup_gain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("convolution", FunctionMetadata {
            name: "convolution",
            description: "TODO: Add description for convolution",
            params: vec![],
            example: "",
            category: "Effects",
        });

        m.insert("cosine", FunctionMetadata {
            name: "cosine",
            description: "TODO: Add description for cosine",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("curve", FunctionMetadata {
            name: "curve",
            description: "TODO: Add description for curve",
            params: vec![
                ParamMetadata {
                    name: "start",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "end",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "duration",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "curve",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("cut", FunctionMetadata {
            name: "cut",
            description: "TODO: Add description for cut",
            params: vec![
                ParamMetadata {
                    name: "group",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Modifiers",
        });

        m.insert("cut_group", FunctionMetadata {
            name: "cut_group",
            description: "TODO: Add description for cut_group",
            params: vec![
                ParamMetadata {
                    name: "group",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Modifiers",
        });

        m.insert("decimator", FunctionMetadata {
            name: "decimator",
            description: "TODO: Add description for decimator",
            params: vec![
                ParamMetadata {
                    name: "factor",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("dist", FunctionMetadata {
            name: "dist",
            description: "TODO: Add description for dist",
            params: vec![
                ParamMetadata {
                    name: "drive",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mix",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("djf", FunctionMetadata {
            name: "djf",
            description: "TODO: Add description for djf",
            params: vec![
                ParamMetadata {
                    name: "value",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("envelope", FunctionMetadata {
            name: "envelope",
            description: "TODO: Add description for envelope",
            params: vec![
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "decay",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "sustain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("env_trig", FunctionMetadata {
            name: "env_trig",
            description: "TODO: Add description for env_trig",
            params: vec![
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "decay",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "sustain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("eq", FunctionMetadata {
            name: "eq",
            description: "TODO: Add description for eq",
            params: vec![
                ParamMetadata {
                    name: "low_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "low_gain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "low_q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mid_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mid_gain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mid_q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "high_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "high_gain",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "high_q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("every_effect", FunctionMetadata {
            name: "every_effect",
            description: "TODO: Add description for every_effect",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("every_val", FunctionMetadata {
            name: "every_val",
            description: "TODO: Add description for every_val",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("expand", FunctionMetadata {
            name: "expand",
            description: "TODO: Add description for expand",
            params: vec![
                ParamMetadata {
                    name: "threshold",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "ratio",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("fchorus", FunctionMetadata {
            name: "fchorus",
            description: "TODO: Add description for fchorus",
            params: vec![
                ParamMetadata {
                    name: "separation",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "variation",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mod_frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("fm", FunctionMetadata {
            name: "fm",
            description: "TODO: Add description for fm",
            params: vec![
                ParamMetadata {
                    name: "carrier_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "modulator_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mod_index",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("fm_crossmod", FunctionMetadata {
            name: "fm_crossmod",
            description: "TODO: Add description for fm_crossmod",
            params: vec![
                ParamMetadata {
                    name: "carrier",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "modulator",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mod_depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("formant", FunctionMetadata {
            name: "formant",
            description: "TODO: Add description for formant",
            params: vec![
                ParamMetadata {
                    name: "source",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "f1",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "f2",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "f3",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "bw1",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "bw2",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "bw3",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("freeze", FunctionMetadata {
            name: "freeze",
            description: "TODO: Add description for freeze",
            params: vec![
                ParamMetadata {
                    name: "trigger",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("if", FunctionMetadata {
            name: "if",
            description: "TODO: Add description for if",
            params: vec![
                ParamMetadata {
                    name: "condition",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "then_signal",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "else_signal",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("impulse", FunctionMetadata {
            name: "impulse",
            description: "TODO: Add description for impulse",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("irand", FunctionMetadata {
            name: "irand",
            description: "TODO: Add description for irand",
            params: vec![
                ParamMetadata {
                    name: "max",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("lag", FunctionMetadata {
            name: "lag",
            description: "TODO: Add description for lag",
            params: vec![
                ParamMetadata {
                    name: "input",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "lag_time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("latch", FunctionMetadata {
            name: "latch",
            description: "TODO: Add description for latch",
            params: vec![
                ParamMetadata {
                    name: "gate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("line", FunctionMetadata {
            name: "line",
            description: "TODO: Add description for line",
            params: vec![
                ParamMetadata {
                    name: "start",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "end",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("min", FunctionMetadata {
            name: "min",
            description: "TODO: Add description for min",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m.insert("mix", FunctionMetadata {
            name: "mix",
            description: "TODO: Add description for mix",
            params: vec![
                ParamMetadata {
                    name: "a",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "b",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mix",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("multitap", FunctionMetadata {
            name: "multitap",
            description: "TODO: Add description for multitap",
            params: vec![
                ParamMetadata {
                    name: "time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "taps",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("n", FunctionMetadata {
            name: "n",
            description: "TODO: Add description for n",
            params: vec![
                ParamMetadata {
                    name: "value",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("noise", FunctionMetadata {
            name: "noise",
            description: "TODO: Add description for noise",
            params: vec![],
            example: "",
            category: "Generators",
        });

        m.insert("note", FunctionMetadata {
            name: "note",
            description: "TODO: Add description for note",
            params: vec![
                ParamMetadata {
                    name: "value",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("organ", FunctionMetadata {
            name: "organ",
            description: "TODO: Add description for organ",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("pan2_l", FunctionMetadata {
            name: "pan2_l",
            description: "TODO: Add description for pan2_l",
            params: vec![
                ParamMetadata {
                    name: "input",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "position",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("pan2_r", FunctionMetadata {
            name: "pan2_r",
            description: "TODO: Add description for pan2_r",
            params: vec![
                ParamMetadata {
                    name: "input",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "position",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("peak_follower", FunctionMetadata {
            name: "peak_follower",
            description: "TODO: Add description for peak_follower",
            params: vec![
                ParamMetadata {
                    name: "attack_time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release_time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("ph", FunctionMetadata {
            name: "ph",
            description: "TODO: Add description for ph",
            params: vec![
                ParamMetadata {
                    name: "rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "feedback",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "stages",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("pingpong", FunctionMetadata {
            name: "pingpong",
            description: "TODO: Add description for pingpong",
            params: vec![
                ParamMetadata {
                    name: "time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "feedback",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("pink", FunctionMetadata {
            name: "pink",
            description: "TODO: Add description for pink",
            params: vec![],
            example: "",
            category: "Generators",
        });

        m.insert("pluck", FunctionMetadata {
            name: "pluck",
            description: "TODO: Add description for pluck",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "damping",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("pm", FunctionMetadata {
            name: "pm",
            description: "TODO: Add description for pm",
            params: vec![
                ParamMetadata {
                    name: "carrier_freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "modulation",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mod_index",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("probe", FunctionMetadata {
            name: "probe",
            description: "TODO: Add description for probe",
            params: vec![
                ParamMetadata {
                    name: "filename",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "duration",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("rand", FunctionMetadata {
            name: "rand",
            description: "TODO: Add description for rand",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m.insert("release", FunctionMetadata {
            name: "release",
            description: "TODO: Add description for release",
            params: vec![
                ParamMetadata {
                    name: "time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Modifiers",
        });

        m.insert("resonz", FunctionMetadata {
            name: "resonz",
            description: "TODO: Add description for resonz",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "q",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("rhpf", FunctionMetadata {
            name: "rhpf",
            description: "TODO: Add description for rhpf",
            params: vec![
                ParamMetadata {
                    name: "cutoff",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "resonance",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("ring", FunctionMetadata {
            name: "ring",
            description: "TODO: Add description for ring",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("rlpf", FunctionMetadata {
            name: "rlpf",
            description: "TODO: Add description for rlpf",
            params: vec![
                ParamMetadata {
                    name: "cutoff",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "resonance",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("rms", FunctionMetadata {
            name: "rms",
            description: "TODO: Add description for rms",
            params: vec![
                ParamMetadata {
                    name: "window_size",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("run", FunctionMetadata {
            name: "run",
            description: "TODO: Add description for run",
            params: vec![
                ParamMetadata {
                    name: "n",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("saw_hz", FunctionMetadata {
            name: "saw_hz",
            description: "TODO: Add description for saw_hz",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("saw_trig", FunctionMetadata {
            name: "saw_trig",
            description: "TODO: Add description for saw_trig",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("scan", FunctionMetadata {
            name: "scan",
            description: "TODO: Add description for scan",
            params: vec![
                ParamMetadata {
                    name: "start",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "end",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("sc_comp", FunctionMetadata {
            name: "sc_comp",
            description: "TODO: Add description for sc_comp",
            params: vec![
                ParamMetadata {
                    name: "sidechain_input",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "threshold",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "ratio",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "attack",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "release",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("schmidt", FunctionMetadata {
            name: "schmidt",
            description: "TODO: Add description for schmidt",
            params: vec![
                ParamMetadata {
                    name: "high_threshold",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "low_threshold",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Utilities",
        });

        m.insert("segments", FunctionMetadata {
            name: "segments",
            description: "TODO: Add description for segments",
            params: vec![
                ParamMetadata {
                    name: "levels_string",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "times_string",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Envelopes",
        });

        m.insert("select", FunctionMetadata {
            name: "select",
            description: "TODO: Add description for select",
            params: vec![
                ParamMetadata {
                    name: "index",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("sew", FunctionMetadata {
            name: "sew",
            description: "TODO: Add description for sew",
            params: vec![
                ParamMetadata {
                    name: "a",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "b",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "pattern",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("sine_trig", FunctionMetadata {
            name: "sine_trig",
            description: "TODO: Add description for sine_trig",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("slowcat", FunctionMetadata {
            name: "slowcat",
            description: "TODO: Add description for slowcat",
            params: vec![
                ParamMetadata {
                    name: "patterns",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("soft_saw", FunctionMetadata {
            name: "soft_saw",
            description: "TODO: Add description for soft_saw",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("sometimes_by_val", FunctionMetadata {
            name: "sometimes_by_val",
            description: "TODO: Add description for sometimes_by_val",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("sometimes_effect", FunctionMetadata {
            name: "sometimes_effect",
            description: "TODO: Add description for sometimes_effect",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("sometimes_val", FunctionMetadata {
            name: "sometimes_val",
            description: "TODO: Add description for sometimes_val",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("square_hz", FunctionMetadata {
            name: "square_hz",
            description: "TODO: Add description for square_hz",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("square_trig", FunctionMetadata {
            name: "square_trig",
            description: "TODO: Add description for square_trig",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("stack", FunctionMetadata {
            name: "stack",
            description: "TODO: Add description for stack",
            params: vec![
                ParamMetadata {
                    name: "patterns",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("struct", FunctionMetadata {
            name: "struct",
            description: "TODO: Add description for struct",
            params: vec![
                ParamMetadata {
                    name: "pattern",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("svf_bp", FunctionMetadata {
            name: "svf_bp",
            description: "TODO: Add description for svf_bp",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "resonance",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("svf_notch", FunctionMetadata {
            name: "svf_notch",
            description: "TODO: Add description for svf_notch",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "resonance",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Filters",
        });

        m.insert("tape", FunctionMetadata {
            name: "tape",
            description: "TODO: Add description for tape",
            params: vec![
                ParamMetadata {
                    name: "time",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "feedback",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "wow_rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "wow_depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "flutter_rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "flutter_depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "saturation",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "mix",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("timer", FunctionMetadata {
            name: "timer",
            description: "TODO: Add description for timer",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m.insert("trem", FunctionMetadata {
            name: "trem",
            description: "TODO: Add description for trem",
            params: vec![
                ParamMetadata {
                    name: "rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("triangle", FunctionMetadata {
            name: "triangle",
            description: "TODO: Add description for triangle",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("triangle_hz", FunctionMetadata {
            name: "triangle_hz",
            description: "TODO: Add description for triangle_hz",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("tri_trig", FunctionMetadata {
            name: "tri_trig",
            description: "TODO: Add description for tri_trig",
            params: vec![
                ParamMetadata {
                    name: "freq",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Oscillators",
        });

        m.insert("unipolar", FunctionMetadata {
            name: "unipolar",
            description: "TODO: Add description for unipolar",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m.insert("unit", FunctionMetadata {
            name: "unit",
            description: "TODO: Add description for unit",
            params: vec![
                ParamMetadata {
                    name: "mode",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Modifiers",
        });

        m.insert("vib", FunctionMetadata {
            name: "vib",
            description: "TODO: Add description for vib",
            params: vec![
                ParamMetadata {
                    name: "rate",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "depth",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("vowel", FunctionMetadata {
            name: "vowel",
            description: "TODO: Add description for vowel",
            params: vec![
                ParamMetadata {
                    name: "pattern",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Effects",
        });

        m.insert("waveguide", FunctionMetadata {
            name: "waveguide",
            description: "TODO: Add description for waveguide",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "damping",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "pickup_position",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("wavetable", FunctionMetadata {
            name: "wavetable",
            description: "TODO: Add description for wavetable",
            params: vec![
                ParamMetadata {
                    name: "frequency",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Synths",
        });

        m.insert("wchoose", FunctionMetadata {
            name: "wchoose",
            description: "TODO: Add description for wchoose",
            params: vec![
                ParamMetadata {
                    name: "options",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("wedge", FunctionMetadata {
            name: "wedge",
            description: "TODO: Add description for wedge",
            params: vec![
                ParamMetadata {
                    name: "a",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "b",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                },
                ParamMetadata {
                    name: "pattern",
                    param_type: "signal",
                    optional: false,
                    default: None,
                    description: "TODO: Add description",
                }
            ],
            example: "",
            category: "Transforms",
        });

        m.insert("whenmod_effect", FunctionMetadata {
            name: "whenmod_effect",
            description: "TODO: Add description for whenmod_effect",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("whenmod_val", FunctionMetadata {
            name: "whenmod_val",
            description: "TODO: Add description for whenmod_val",
            params: vec![],
            example: "",
            category: "Transforms",
        });

        m.insert("wrap", FunctionMetadata {
            name: "wrap",
            description: "TODO: Add description for wrap",
            params: vec![],
            example: "",
            category: "Utilities",
        });

        m
    };
}
